### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on any page

### ISSUE THREAD

**Issue by FredericMartinez** [UltimateModuleCreator/umc#13]
Hello Marius :)

Every URL is redirected with a infinite public folder cascade.

URL: http://umc.test/public/index.php/settings

Is redirected to:
http://umc.test/public/index.php/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/index.php

Here a small video: https://www.screencast.com/t/jNR0llMyDkP

**Comment by UltimateModuleCreator** [comment]
@FredericMartinez Strange. 
That does not happen on my side. but honestly, I used only 'localhost' as url so far.  
Will investigate and get back to you.
Thanks for reporting this.

**Comment by FredericMartinez** [comment]
Info: I use [Valet Plus](https://github.com/weprovide/valet-plus) on MacOS in a standard configuration way.

**Comment by UltimateModuleCreator** [comment]
@FredericMartinez I wasn't able to reproduce this, but here is what you can try. There is a file `index.php` in the root of the project that does this:

```
<?php
header("Location: public/index.php");
```
Try removing it.  
If that does not work, replace its contents with the contents from `public/index.php` and adjust the relative paths involved in it.

**Comment by sidealice** [comment]
i have same problem at the backend.
magento2.3

**Comment by mlaurense** [comment]
Fixed! Go into the public subdirectory, and issue a `valet link umc.test`. This will link the public directory to the webroot.
