### ISSUE TITLE
About working on Nginx

### ISSUE THREAD

**Issue by mozgbrasil** [UltimateModuleCreator/umc#15]
Ola Boa Tarde, tudo bem

Conforme imagens vemos que não funciona no Nginx, tem alguma dica ?

![captura de tela de 2019-02-08 12-21-08](https://user-images.githubusercontent.com/17202780/52484709-2cebf880-2b9e-11e9-84f7-07552fc1b794.png)
![captura de tela de 2019-02-08 12-21-10](https://user-images.githubusercontent.com/17202780/52484711-2cebf880-2b9e-11e9-82cb-160974879892.png)
![captura de tela de 2019-02-08 12-21-11](https://user-images.githubusercontent.com/17202780/52484712-2cebf880-2b9e-11e9-9ebc-b47def1ac30d.png)
![captura de tela de 2019-02-08 12-34-21](https://user-images.githubusercontent.com/17202780/52484713-2d848f00-2b9e-11e9-8baf-f83082fa1b60.png)
![captura de tela de 2019-02-08 12-34-30](https://user-images.githubusercontent.com/17202780/52484714-2d848f00-2b9e-11e9-862a-be0f1f6caba4.png)
![captura de tela de 2019-02-08 12-34-34](https://user-images.githubusercontent.com/17202780/52484715-2d848f00-2b9e-11e9-9830-a627ea717d36.png)
![captura de tela de 2019-02-08 12-34-39](https://user-images.githubusercontent.com/17202780/52484716-2d848f00-2b9e-11e9-9ba3-3d6d53637867.png)

**Comment by UltimateModuleCreator** [comment]
@mozgbrasil English Please. Most likely you don't have mod rewrite enabled: https://www.digitalocean.com/community/questions/enabling-nginx-mod_rewrite

**Comment by mozgbrasil** [comment]
Sorry for not interacting in English I really confused myself but thank you very much for the tip and have a great week
