### ISSUE TITLE
Generating wrong frontend router

### ISSUE THREAD

**Issue by zaheerbadi** [UltimateModuleCreator/umc#17]
**I am testing this on Windows Environment with PHP 7.2**
I tried with creating new module with this and found that when we inset it to main top navigation it redirect to 404 due to wrong link.

It seems frontname is not appending in the url.

I manually change url to frontname it started working.

Before :: http://prntscr.com/mzuslz
After :: http://prntscr.com/mzus1v

also it is not working with Image or FIle upload wrong route configure in ui file

**Comment by UltimateModuleCreator** [comment]
@zaheerbadi 
Just to make sure, you did fill in a value for the field `Frontend Url Keu`, right?

![image](https://user-images.githubusercontent.com/11390799/56443211-5347b600-62fc-11e9-895b-1acc793bca3f.png)

**Comment by UltimateModuleCreator** [comment]
@zaheerbadi In the folder `var/umc` there should be a `yml` file with the same name as the module you created. Can you please send it to me so I can replicate the module on my side and debug it? You can send it to ultimate.module.creator@gmail.com

**Comment by UltimateModuleCreator** [comment]
This should be fixed in 4.0.0
