### ISSUE TITLE
The label_singular field tip is not completely visible

### ISSUE THREAD

**Issue by yutv** [UltimateModuleCreator/umc#24]
On the Edit Entity form when you move mouse over the label_singular field the tip shows but it is cut from beginning, see the screenshot below. Making the tip a bit wider may resolve the problem.

![image](https://user-images.githubusercontent.com/1616522/63244436-0baf4780-c266-11e9-922e-81241193b190.png)

**Comment by UltimateModuleCreator** [comment]
The UI was changed. This is obsolete in version 4.0.0
