### ISSUE TITLE
Table with more than 16 attributes causes failure on SQL install

### ISSUE THREAD

**Issue by lanrosta** [UltimateModuleCreator/umc#34]
SQLSTATE[42000]: Syntax error or access violation: 1070 Too many key parts specified; max 16 parts allowed

This happens when I create a table with more than 16 fields (attributes). I need more than 16 fields here and older UMC1 handled these fine. What gives?

Also, I do not see any Setup/InstallShema.php files being created. How is it installing the tables then?

**Comment by lanrosta** [comment]
Edit: For Magento 2.3, it uses a declarative setup... https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html

**Comment by lanrosta** [comment]
If you run into this issue when installing your custom module, have a look at your module's 'etc/db_schema.xml' file and look at the `<index referenceId="VENDOR_MODULE_FULLTEXT" indexType="fulltext">` section. Make sure you have 16 or less `<column>` items in this section, otherwise an error is thrown when trying to install the module.

Note that this is a Magento 2.3 limitation and not UMC.

**Comment by UltimateModuleCreator** [comment]
IN version 4.0 of UMC you can decide which attributes go into the full text search. This way it's the user responsibility to not go over the allowed number of attributes.
