### ISSUE TITLE
Save and continue

### ISSUE THREAD

**Issue by manuelcanepa** [UltimateModuleCreator/umc#35]
It will be amazing if the "Add New Attribute" form has a button "save and continue" as default button. When you clic on it, the form will be save and a new attribute form will shown so you can create a new one.

**Comment by UltimateModuleCreator** [comment]
You have now default settings. It's not exactly what you needed, but you can set values in one place and new attributes will have those values.

**Comment by UltimateModuleCreator** [comment]
@manuelcanepa Ok, I think I misread the issue the first time. I read it again and realized this does not apply because the UI was changed and there are no more popups to add entities and or attributes
