### ISSUE TITLE
Space before entity name

### ISSUE THREAD

**Issue by manuelcanepa** [UltimateModuleCreator/umc#36]
https://github.com/UltimateModuleCreator/umc/blob/b843f2d4b1a0738f4808e750d2ba7c57f23371fd/templates/source/Model/EntityRepository.php.html.twig#L200

Without space between `remove` and `{{ entity.getLabelSingular()|ucfirst }}` the message return: `Unable to removeEntityName %1`

**Comment by UltimateModuleCreator** [comment]
This should be fiexed in version 4.0.0
