### ISSUE TITLE
Image Field on Admin Edit: outputProcessor call should be uploaderPool call

### ISSUE THREAD

**Issue by lanrosta** [UltimateModuleCreator/umc#37]
When I have an image field in my module, and I try to edit a record in the admin, I get an error about cannot getUploader. If my module's name is 'Artist', then the 'Model/Artist.php' file gets generated with this line in the constructor:  '$this->outputProcessor = $outputProcessor;'. This causes an error when trying to access the Edit page for a record. Instead, this should be  $this->uploaderPool = $uploaderPool;. This looks like an issue in Entity.php.html.twig at line 103.

**Comment by UltimateModuleCreator** [comment]
This should be fiexed in version 4.0.0
