### ISSUE TITLE
Image Uploading in admin area does not work when the Module Name has capital letters after the first character

### ISSUE THREAD

**Issue by lanrosta** [UltimateModuleCreator/umc#38]
I created a module called 'Vendor/CustomsGallery/' that has an image field in it. On Magento 2.3.3 when I try to add a record from the admin area, I get an error 'A technical problem with the server created an error.' when I try to upload an image. I looked at closely at all the code, and compared it to another module I made called 'Vendor/Artists/' that works fine. It appears the issue was the naming of the module. I had to rename it to 'Vendor/Customsgallery' to get it to work.

**Comment by UltimateModuleCreator** [comment]
This should be fiexed in version 4.0.0
