### ISSUE TITLE
Is this Repo ever going to be updated?

### ISSUE THREAD

**Issue by lanrosta** [UltimateModuleCreator/umc#39]
It's been a long time since the author of this repo has made any updates. I like UMC, and I've used it since Magento 1, and I loved the features it provided back in the Magento 1 version (mainly table relationships). This new V2 version is a great start, but it does not even provide features the V1 version did, and it looks as if it won't be updated anytime soon with fixes, or table realtionships added. So, I'd like to ask the author of this repo if they are still planning to update it, or is this repo dead?

**Comment by UltimateModuleCreator** [comment]
@lanrosta thanks for the kind words about the magento 1 version. 
Yes, I have plans to update this with bug fixes and new features. But i don't really have the time to do them (as you can see, I am even answering late to your message. Sorry about that). Magento 1 was not changing that often. It was easier to develop new stuff on that version of the module. It is kind of hard to keep up with the changes in magento 2.

**Comment by lanrosta** [comment]
Thanks for the reply Marius. I know M2 keeps changing things around, making it difficult to get a good grasp on development moving forward. So, I understand the plight, and also this is a side project of yours that has helped many many folks struggling to learn Magento module development. I certainly do appreciate the efforts you have made and shared with us. Just hoping for more of this greatness moving forward in M2. Thanks again.

**Comment by UltimateModuleCreator** [comment]
@lanrosta still not there, but something started to happen: https://github.com/UltimateModuleCreator/umc/tree/umc-42 (work in progress)

**Comment by UltimateModuleCreator** [comment]
@lanrosta I now have a definitive answer. Yes, this repo is updated. There is a version 4.0.0
