### ISSUE TITLE
Dockerize UMC

### ISSUE THREAD

**Issue by UltimateModuleCreator** [UltimateModuleCreator/umc#50]

**Comment by carlos-reynosa** [comment]
It would be nice if docker was the only requirement. I would like to just run  `docker-compose up -d ` and head to the URL and start using the application. I was able to set up the application on my own but it had 2 other requirements before i could get started:

1. PHP & Composer
   * I used the magento cloud docker recommended command for installing composer dependencies using a docker image. 
2. PHP & Web Server configuration 
    *  I used [LAMP stack  docker project](https://github.com/sprintcube/docker-compose-lamp) but its probably overkill since it has mysql and other apps in it. I had to edit the php image to make sure that it had the correct extensions. 

### PHP & Composer Requirements
The Magento cloud docker project suggests the following command for installing composer dependencies in a dockerized way:
 
`docker run -it  -v $(pwd):/app/:delegated -v ~/.composer/:/root/.composer/:delegated magento/magento-cloud-docker-php:7.3-cli-1.1 bash -c "composer install&&chown www. /app/" `

This should remove local php and composer requirements. I actually used this command on this project to get this up and running. I think something like this would be good to put into the Readme or somehow ingrate it as part of the `docker-compose up -d` process. 

Docker Composer Image:

* https://hub.docker.com/_/composer

### PHP & Web Server Requirements
Maybe a more light weight php-apache image solution than the one i used:

* https://hub.docker.com/_/php

**Comment by florinel-chis** [comment]
`php -S localhost:80` (or whatever port you fancy) seems to work good enough.

**Comment by UltimateModuleCreator** [comment]
This should be available starting version 4.3.3
