### ISSUE TITLE
Add a "disable in admin end" setting for attributes

### ISSUE THREAD

**Issue by thomasnares** [UltimateModuleCreator/umc#56]
I added a "Disable in admin" checkbox for entity attributes in Magento modules (by modifying MagentoBundle/Model/Attribute, MagentoBundle/Resources/config/form/attribute.yml, and the twig templates),

would you add this feature in your project ? 
It helps us managing which attribute should be user set or code set. 

UMC interface : 
![Screenshot 2020-10-06 at 09 53 14](https://user-images.githubusercontent.com/1589947/95174003-c3305180-07b9-11eb-9043-186f948c0bfa.png)

Magento Admin : 
![Screenshot 2020-10-06 at 09 54 07](https://user-images.githubusercontent.com/1589947/95174107-e2c77a00-07b9-11eb-9f74-1aac04d4cec2.png)

**Comment by UltimateModuleCreator** [comment]
@thomasnares 
The use of these disabled fields is not that common. I don't want to add extra inputs to fill in unless they have a wider usage. I actually removed some of the inputs from previous versions for the same reason.  
And if you need fields that are calculated you will implement the calculation algorithm anywayt. So you can make the field disabled just by adding one line in an xml file when you implement the calculation for it. 
I will close this for now
