### ISSUE TITLE
Create one-to-many relation support for entities

### ISSUE THREAD

**Issue by UltimateModuleCreator** [UltimateModuleCreator/umc#7]

**Comment by lanrosta** [comment]
It's December 2019. Any word on support for Relations? This is pretty important functionality found in older UMC products.

**Comment by UltimateModuleCreator** [comment]
@lanrosta Sorry. this project was put aside due to lack of time. No news yet on relations support. Sorry.

**Comment by UltimateModuleCreator** [comment]
This is too big of a task to fit in one release. Converting this to "Support one-to-many relations". Many-to-many relations will be handled in #46

**Comment by UltimateModuleCreator** [comment]
This should be supported starting version 4.2.0
